- name: Bootstrap
  hosts: all
  become: true
  roles:
    - rmb938.bootstrap
  vars:
    step_ca_url: https://cuboid-topi.rmb1993-gmail-com.ca.smallstep.com

- name: Step CA RA
  hosts: all
  become: true
  roles:
    - step-ca-ra
